### ISSUE TITLE
Add multiple Configs

### ISSUE THREAD

**Issue by stbischof** [amitjoy/osgifx#395]
**Is your feature request related to a problem? Please describe.**
I would like do add MultipleConigs for the same Factory-Config-PID and Config-PID

**Describe the solution you'd like**
Split The Configurations view into 2 Parts:
Configutation-Templates (Factory-Config-PID and Config-PID with there default values ) and Configurations that showes the really un the system used configurations

also the + buttons are a bit missleading. them could mean more details. but also add new configutation.

**Describe alternatives you've considered**
.

**Additional context**

shows that ther is no way to add an additional config for the same factory
[Screencast from 2022-11-28 17-23-18.webm](https://user-images.githubusercontent.com/33224746/204330720-be3638a7-3224-4ced-b985-d6f424cfedfc.webm)

**Comment by amitjoy** [comment]
This feature has already been implemented. You have to go to `Configurations`, search for the factory PID in the list by right clicking on the `PID/Factory PID` column which will open a box to filter by string. Once you find the factory PID in the list, you can expand the row, enter the configurations for the properties and save - this will create a new configuration for that factory PID which you will find in the same list of configurations. You can create multiple configurations by opening the factory PID row entry as many times as you want.

**Comment by stbischof** [comment]
But isn't is also possible in osgi to do the same with a normal pid and not just Factory pid?

**Comment by amitjoy** [comment]
In OSGi, every configuration is uniquely identified by a single PID, hence, we cannot create multiple configurations for a single PID, whereas, a factory PID allows to create multiple configurations. Note that, when we create a configuration under a factory PID, the configuration which will be created will have its unique PID automatically generated by the ConfigAdmin bundle.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by stbischof** [comment]
Lets take 

org.apache.felix.http

I am pretty sure that i could configure this in a way that i have 2 http times on different ports

**Comment by amitjoy** [comment]
`org.apache.felix.http` is not a factory PID. That's why, it should not be possible to create multiple configurations using `org.osgi.service.cm.ConfigurationAdmin.createFactoryConfiguration(factoryPID, location)`.

**Comment by stbischof** [comment]
this is was i thought since BJ teaches me others:




```
@Designate(factory = false, ocd = Config.class)
@Component(service = Closeable.class ,configurationPid = Foo.PID_FOOO)
public class Foo implements Closeable {

   public static final String PID_FOOO = "fooo";

    @ObjectClassDefinition
    @interface Config {
        String c();
    }

    private UUID uuid = UUID.randomUUID();

    @Activate
    public void act(Config c) {
        System.out.println("act c - " + uuid);
    }
    
    @Deactivate
    public void deact(Config c) {
        System.out.println("deact c - " + uuid);
    }

    @Override
    public void close() throws IOException {

    }
    @Override
        public String toString() {
            return "name c - " + uuid;
        }

}
```
```
public class TestCM {

    @InjectBundleContext
    BundleContext bc;

    @InjectService(timeout = 5000)
    ConfigurationAdmin ca;

    @Test
    public void theTest(@InjectService ServiceAware<Closeable> sac) throws Exception {
        Configuration c1 = ca.getFactoryConfiguration("fooo", "1", "?");
        c1.update(Dictionaries.dictionaryOf("c", "1"));

        Configuration c2 = ca.getFactoryConfiguration("fooo", "2", "?");
        c2.update(Dictionaries.dictionaryOf("c", "2"));

        Thread.sleep(  2 * 1000);

        sac.getServices()
                .forEach(System.out::println);

        Thread.sleep(60 * 60 * 1000);

    }
}
```


Ressule:
```
act c - 84d6515c-e098-4aee-99c7-6575640dfab4
deact c - 84d6515c-e098-4aee-99c7-6575640dfab4
act c - 17ca1597-548d-48c8-84bb-6b865480c39c
act c - 2815013f-76ea-4393-a5c0-65a19305ab20
name c - 2815013f-76ea-4393-a5c0-65a19305ab20
name c - 17ca1597-548d-48c8-84bb-6b865480c39c
```

**Comment by stbischof** [comment]
and when doing 2 felix http whiteboard configs  i have port 8081 and 8082 open.


```
    @Test
    public void theTestJetty(@InjectService ServiceAware<HttpServiceRuntime> sac) throws Exception {
        Configuration c1 = ca.getFactoryConfiguration("org.apache.felix.http", "1", "?");
        c1.update(Dictionaries.dictionaryOf("org.osgi.service.http.port", "8081"));

        Configuration c2 = ca.getFactoryConfiguration("org.apache.felix.http", "2", "?");
        c2.update(Dictionaries.dictionaryOf("org.osgi.service.http.port", "8082"));
```

**Comment by cziegeler** [comment]
The Apache Felix example is misleading. The implementation supports both (due to compatibility reasons) a singleton configuration with the PID o.a.f.http and factory configurations with the factory pid o.a.f.http (looking back, we should have picked a different factory pid...)

**Comment by cziegeler** [comment]
I think that only works with DS components - though I would need to read up the spec to see whether that is actually desired or a bug

**Comment by amitjoy** [comment]
That's really strange that even if a configuration is not a factory, is still able to be used to create factory configurations. We have to check if this behaviour complies with the spec.

**Comment by juergen-albert** [comment]
I found this, which seems to describe the behavior discussed here:

```
112.7.1.3 Optional Configuration Policy
For configuration-policy of optional, component configurations do not require Configuration objects. Since matching Configuration objects are optional, component configurations can be satisfied with zero or more matched configuration PIDs. If a Configuration object is then created which matches a configuration PID, this is a configuration change for the component configurations that are not using the created Configuration object. If a Configuration object is deleted which matches a configuration PID, this is a configuration change for the component configurations using the deleted Configuration object.

Furthermore, with a factory configuration matching a configuration PID, the factory configuration can provide zero or more Configuration objects which will result in a component configuration for each Configuration object or a single component configuration when zero matching Configuration objects are provided. With a factory component, multiple component configurations can be created all using the Configuration objects matching the configuration PIDs.
```

It does not directly describe the behavior that it removes the existing service and creates one or more new instances correlating to the factory configurations.

**Comment by stbischof** [comment]
This `factory=false` seems just to make that the configuration is required.
[spec](https://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.component.html#org.osgi.service.component.annotations.Component.configurationPolicy--)

**Comment by laeubi** [comment]
I think different things are mixed up here. First there is the CM spec and that distinguishes two cases:

1. [Managed Service](https://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.cm.html#i1233865) that is usually bound to one specific _Configuration PID_
2.[Managed Service Factory](https://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.cm.html#i1299227) that is usually bound to one specific _Factor PID_ and creates a service for each derived _Configuration PID_

Then there is the `ConfigurationAdmin` that has to variants:

1. `getConfiguration` (that might return an non existing one) 
2. createFactoryConfiguration (to create a new factory one)

Further on we have DS, that allows "instance per configuration", and do not distinguish the two cases, you can use factory configs or you can use a named config.

And finally we have MetaType service to tell what "the string" of a PID should actually mean.

So technically one can't create multiple configs for the same PID (because they are the same and would result always in the same configuration), but DS can handle the case that the "same String" is used to check if there is either a named or a factory configuration and uses this for creating multiple instances, but if such a component  wants to support this it should mention this in their metatype because otherwise no one can know if a string that looks like a PID is meant as a factory or regular pid!

**Comment by pkriens** [comment]
The design of CM is such that each configuration has a PID and optionally a factoryPID. I.e. the factoryPID is a 'group' name. Generally when a factory configuration is created, a unique arbitrary PID name is used. However, a configuration with PID=A and a factoryPID=A should be valid. The same configuration would be a factory configuration AND a singleton configuration ...

* getConfiguration(A) – select(PID=A) orelse new record(service.pid=A, service.factoryPid=null)
* createConfiguration(A) – new record(service.pid=uniqueName(), service.factoryPid=A)

The purpose was to keep the data model very simple, something not unimportant in the late nineties. For this reason we even returned null from `getServiceReferences()` and other places because we had the hare brained idea that this would save memory :-( That said, I think this model worked out pretty well. 

For DS I think we lookup both the singleton and factory configurations and if they exist we use it.

**Comment by amitjoy** [comment]
Thanks everyone for your valuable inputs. As pointed out here as well as in OSGi Development channel, it will not be quite compliant with the spec to enable creation of factory configurations from normal PIDs, even though it works to some extent with DS but at the CM level, it is not allowed.
