### ISSUE TITLE
General DTO-Viewer

### ISSUE THREAD

**Issue by stbischof** [amitjoy/osgifx#396]
**Is your feature request related to a problem? Please describe.**
In OSGi we have Multiple Runtimes that could deliver DTO
- SCRuntime
- HttpWhiteboard
- JaxRs
- Framwork
- CDI
 I con to see the information of this DTO

**Describe the solution you'd like**
Would be great if i could select one of these Runtimes (could also be multiple one of each type)  and  visualize the dto in a tree and see more information on clicking on the nodes.
 also an visual viel like an component diagram would be graeat

**Describe alternatives you've considered**
something like https://github.com/aQute-os/biz.aQute.osgi.util/tree/master/biz.aQute.gogo.commands.provider/src/main/java/biz/aQute/gogo/commands/dtoformatter

**Additional context**
an ui equivalent of
https://github.com/aQute-os/biz.aQute.osgi.util/blob/master/biz.aQute.gogo.commands.provider/src/main/java/biz/aQute/gogo/commands/provider/HTTP.java
https://github.com/aQute-os/biz.aQute.osgi.util/blob/master/biz.aQute.gogo.commands.provider/src/main/java/biz/aQute/gogo/commands/provider/JaxRS.java
https://github.com/aQute-os/biz.aQute.osgi.util/blob/master/biz.aQute.gogo.commands.provider/src/main/java/biz/aQute/gogo/commands/provider/DS.java
https://github.com/aQute-os/biz.aQute.osgi.util/blob/master/biz.aQute.gogo.commands.provider/src/main/java/biz/aQute/gogo/commands/provider/DTOFramework.java

**Comment by amitjoy** [comment]
These informations (except CDI and JAX-RS Whiteboard) are already available in different views in different layouts. If you want a tree-like structure, it could be similar to the DMT view which lists the DMT in a tree view.

This feature sounds very interesting as we can then be able to select any DTO and anyone can visualise it very easily. Since, I am currently working on the search functionality, it might take a while to introduce DTO visualisation as I am working on it in my free time. If you would like, it would be really great if you are interested in contributing as well. Otherwise, I will keep it on my roadmap and once I am done with the search functionality, I will start working on it.
