### ISSUE TITLE
Bundle list is empty

### ISSUE THREAD

**Issue by doggy-dev** [amitjoy/osgifx#602]
**Describe the bug**
After connecting to the agent in my osgi application the bundle and packages list remains empty. Other information can be retrievend

**To Reproduce**
1. Start a Felix container with the agent. 
2. connect to the application
3. wait a bit to retrieve all data
4. open the bundles tab

**Expected behavior**
see all bundles from the application

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Version 13.3.1

**Comment by amitjoy** [comment]
Could you kindly tell me how you are connecting to the remote OSGi runtime? Socket or MQTT? I guess you are connecting over sockets, right? When you connect to the agent, it takes a bit of time before it retrieves all the information from the remote agent and in the overview tab, all the informations will be shown. Could you kindly also share some screenshot? like how does your configuration look? How does it look after the informations are retrieved from the remote runtime? etc.

**Comment by amitjoy** [comment]
It seems the relevant information for bundles isn't retrieved and that's why, bundle count is 0 in the overview tab. If you go to Bundles Tab, you will find refresh button at the bottom which will try to fetch the bundles list once again. Otherwise, you can click on the play button situated at the bottom status bar in the Overview tab which will retrieve all the information once again.

**Comment by amitjoy** [comment]
By the way, did you have an older version of OSGi.fx already installed earlier? If yes, you need to clean the OSGi storage before updating to a newer version since the older bundles can mess things up with newer bundles. This is a drawback as of now. I am trying to find a seamless solution for this though but as of now, for updating to newer version of OSGi.fx, you should always clean the previous OSGi storage. 

To delete the storage, you have to delete `~/.osgifx-ws/`

**Comment by doggy-dev** [comment]
I've not installed OSGi.fx before. Hitting the refresh button didn't help unfortunately. Can I provide you some other logs, that can help you?

**Comment by amitjoy** [comment]
Sure, that would be very helpful.

**Comment by doggy-dev** [comment]
Let me know which logs you need.
I need a couple of minutes to restart.

**Comment by amitjoy** [comment]
`fx.log` should be sufficient - I noticed that there is an `IndexOutOfBoundsException` in our previous log which has been thrown from JavaFX itself - that's quite weird too. I am also using macOS (13.3.1) and it works without any exception.

**Comment by doggy-dev** [comment]
No luck :/. Maybe the problem is the agent and the fact it's running in a felix container?

[fx.log](https://github.com/amitjoy/osgifx/files/11515639/fx.log)

**Comment by amitjoy** [comment]
I am not sure where the problem could be since I am also using a remote Felix runtime with 300+ bundles. That's quite strange.

**Comment by doggy-dev** [comment]
OK, I'll try to debug the agent tomorrow and will let you know what I found.

**Comment by amitjoy** [comment]
Thanks a lot 👍 In the meanwhile, I will check the logs to see if I find something to immediately take care of.

**Comment by amitjoy** [comment]
Instead of connecting to the remote OSGi runtime, could you kindly try to connect to the local agent - `Help ⇢ Connect to Local Agent` - this will let you connect to the OSGi runtime which OSGi.fx itself is running on. I just want to check if the problem you are encountering could be a problem with unstable local network. The local agent internally uses the same communication mechanism. Internally it connects to `localhost:1729`.

**Comment by amitjoy** [comment]
I think you are already using OSGi R6+ compliant Felix, otherwise, the agent bundle wouldn't have been resolved at the first place.

**Comment by doggy-dev** [comment]
Yes I'm able to connect to the local agent of osgi.fx. But the network is an ethernet cable so it shouldn't be a problem.
I haven't mention that I'm using a custom osgi application launcher, which could be the reasons for the error. I'll check if this is the case tomorrow.

**Comment by amitjoy** [comment]
Thanks @doggy-dev for your cooperation. It means a lot 👍

**Comment by doggy-dev** [comment]
Hi
I've got it. The problem was that I have a jar which is not a bundle and so it doesn't have a bundle name. This throws a NPE in XBundleDTO Line 110.

I've noticed that there is a unlogged cached exception in XBundleAdmin::get. This hides problems and makes bug fixing harder.

**Comment by amitjoy** [comment]
Thanks a lot for debugging the issue. Could you kindly provide the stacktrace for me to fix? If you like, you could also provide a PR for the fix as well.
